config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/books/highest_ranked' => 'books#highest_ranked'


  resources :reviews, except: :index
  resources :genres

  resources :books do 
    resources :reviews, only: [:new, :show] 
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  has_many :reviews
  has_many :users, through: :reviews


  validates :title, presence: true, uniqueness: true 
  validates :author, presence: true

  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(rating) desc')}

  scope :order_by_reviews, -> {left_joins(:reviews).group(:book_id).order('count(reviews.id) desc').limit(1)}


  def self.alpha
    order(:title)
  end

  def average
    self.reviews.average(:rating).to_f.round(2)
  end
  
  def genre_attributes=(attributes)
    self.genre = Genre.find_or_create_by(attributes) if !attributes['name'].empty?
    self.genre
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books 

    validates :name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :rating, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
  validates :title, presence: true

  validates :book, uniqueness: { scope: :user, message: "This has already been reviewed by you"  }


end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :books, through: :reviews

    validates :username, uniqueness: true, presence: true 

    has_secure_password

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.username = response[:info][:name]
            u.password = SecureRandom.hex(15)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

  private

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to login_path if !logged_in?
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        @book = Book.new
        @book.build_genre 
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = session[:user_id]
        if @book.save
            redirect_to book_path(@book)
        else
            render :new
        end
    end

    def index
        @books = Book.alpha
    end

    def show 
        @book = Book.find(params[:id])
    end

    def highest_ranked
        @books = Book.order_by_rating
    end

    private

    def book_params
        params.require(:book).permit(:title, :author, :user_id, :genre_id, genre_attributes: [:name])
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index
        @genres = Genre.all
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :set_review, only: [:show, :destroy, :edit, :update]
    before_action :redirect_if_not_logged_in
    before_action :user_allowed, only: [:edit, :destroy]

    def new
        if @book = Book.find_by_id(params[:book_id])
            @review = @book.reviews.build
        else
            @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        book = Book.find(params[:review][:book_id])

        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def show
        # @review = Review.find_by_id(params[:id])
    end

    def edit
        # if params[:book_id]
        #     book = Book.find_by_id(params[:book_id])
        #     if book.nil?
        #         redirect_to book_path, alert: "Not found"
        #     else
        #         @review = book.posts.find_by(id: params[:id])
        #         redirect_to book_review_path(book), alert: "not found" if @review.nil?
        #     end
        # else
            # @review = Review.find(params[:id])
        # end

    end

    def update
        # @review = Review.find_by_id(params[:id])
        @review.update(review_params)
        redirect_to review_path(@review)
    end

    def destroy
        @review.destroy 
        redirect_to books_path
      end 

    private

    def review_params
        params.require(:review).permit(:book_id, :rating, :title, :content, :user_id)
    end

    def set_review
        @review = Review.find_by_id(params[:id])
    end

    def user_allowed
        if current_user != @review.user
            redirect_to books_path
        end
    end
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end

    def new
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user.try(:authenticate, params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
          else
            flash[:error] = "Login info was incorrect. Please try again."
            redirect_to login_path
        end
    end

    def omniauth
        user = User.from_omniauth(request.env['omniauth.auth'])
        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            redirect_to '/login'
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          render :new
        end
      end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user 
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def nav_bar
        if logged_in? 
            render partial: 'layouts/loggedin_links'
        else
            render partial: 'layouts/loggedout_links'
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def book_id_field(review)
        if review.book.nil?
            select_tag "review[book_id]", options_from_collection_for_select(Book.alpha, :id, :title)
        else
            hidden_field_tag "review[book_id]", review.book_id
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @book}  %>

<%= form_for(@book) do |f| %>

    <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
    </div>

    <p>Select an already existing genre:</p>
    <div>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: 'Select a Genre'  %>
    </div>


    <p> Add a new genre: </p>
    <div>
    <%=f.fields_for :genre do |g| %>
      <%= g.label :name %>
      <%= g.text_field :name %>
    <% end %>
    </div>
    <br>

    <%= f.submit "Add" %>
<% end %>

app/views/books/highest_ranked.html.erb
<h1>Highest Ranked Books on Bookshelf</h1>

<% @books.each do |b| %>
    <h2><%= link_to b.title, book_path(b.id)%> by <%= b.author %> - Average Rating: <%= b.average %> Stars </h2>
<% end %>

app/views/books/index.html.erb
<h1>Books in Bookshelf</h1>

<% @books.each do |b| %>
    <h2><%= link_to b.title, book_path(b.id)%> by <%= b.author %> </h2>
<% end %>

app/views/books/new.html.erb
<h1>Add a New Book to Bookshelf</h1>

<%= render partial: 'form'%>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<h2>By: <%= @book.author %></h2>
<h3>Genre: <%= @book.genre.name %></h2>

<h4> Average Rating: <%= @book.average %></h4>
<h4>Reviews for <%= @book.title %>: </h4>

<% @book.reviews.each do |r| %>
    <ul>
        <li><%= link_to r.title, review_path(r) %> - <%= r.rating %> Stars
    </ul>
<% end %>

<%= link_to "Review this book", new_book_review_path(@book.id) %>

app/views/genres/index.html.erb
<h1>All Genres on Bookshelf</h1>

<ul>
    <% @genres.each do |g| %>
        <li><%= g.name %>
    <% end %>
</ul>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3><%= pluralize(object.errors.count, "error") %> prevented this from being submitted.</h2>
<ul>
    <% object.errors.full_messages.each do |message| %>
        <li>
        <%= message %>
        </li>
    <% end %>
</ul>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Home", user_path(current_user) %> |
<%= link_to "All Books", books_path %> |
<%= link_to "Highest Ranked Books", books_highest_ranked_path %> |
<%= link_to "Add a Book", new_book_path %> |
<%= link_to "Add a Review", new_review_path %> | 
<%= link_to "All Genres", genres_path %> |
<%= link_to "Log Out", logout_path, method: :delete %>

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %>
<%= link_to "Sign Up", signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <%= nav_bar %>
  </div>


  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
   <%= book_id_field(@review) %><br>


    <div>
    <%= f.label :rating %>
    <%= f.number_field :rating, min:0, max:5 %>
    </div>

    <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
    </div>


    <%= f.submit "Submit" %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render partial: 'layouts/errors', locals: {object: @review}  %>

<%= render partial: 'form' %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render partial: 'layouts/errors', locals: {object: @review}  %>

<%= render partial: 'form' %>

app/views/reviews/show.html.erb
<h1><%= @review.book.title %> by <%= @review.book.author %></h1>

<h2><%= @review.title%> - <%= @review.rating%> Stars</h2>

<h3><i>Review by <%= link_to @review.user.username, user_path(@review.user) %></i></h3>

<p><%= @review.content%></p>

<% if @review.user_id == current_user.id %> 
<%= link_to 'Edit', edit_review_path(@review), {method:'get'} %>
  <%= link_to 'Delete', review_path(@review), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %> 

app/views/users/new.html.erb
<h1>Sign up for Bookshelf</h1>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up" %>
<% end %>
<br>
<%= button_to "Sign Up with Google", '/auth/google_oauth2'  %>

app/views/users/show.html.erb
<% if @user == current_user %> 
<h1>Welcome <%= @user.username %></h1>
<h2>Your Books:</h2>
<% else %>
  <h2><%= @user.username%>'s Books Reviewed: </h2>
<% end %>


<% @user.reviews.each do |r| %>
  <ul>
    <%= link_to r.book.title, book_path(r.book) %> - 
    <%= link_to r.rating, review_path(r) %> Stars 
  </ul>
<% end %>